# Определяем сервисы
services:
  # Шаг 3: Сервис PostgreSQL
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  # Шаг 4: Сервис NGINX (веб-сервер)
  web:
    image: nginx:latest
    container_name: my_nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
    links:
      - db

