# pod-with-pvc.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-with-pvc
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /data # Куда монтируем внутри контейнера
      name: local-storage
  volumes:
  - name: local-storage
    persistentVolumeClaim:
      claimName: local-pvc # Имя нашего PVC